### ISSUE TITLE
support AoT compilation?

### ISSUE THREAD

**Issue by nexus-uw** [rangle/angular2-redux-example#271]
Is it possible for this project to support AoT compilation?

**Comment by SethDavenport** [comment]
@nexus-uw this is an example app, not a starter any more. We don't update it as often as the angular2-starter.

If you want to take a crack at it, go ahead and make a PR :)

Otherwise, I know @bennett000 and @watrool have been looking at AoT with angular2-starter.  The last I heard it wasn't working terribly well with webpack although they may have made progress since then. Note that angular-cli doesn't even support AoT yet so it's pretty bleeding edge.

**Comment by SethDavenport** [comment]
Update on this:  angular2-starter now supports AoT. Since this project is a code example and not a starter kit any more I'm going to leave it how it is.

If the CLI ever supports our cssnext toolchain I might re-work this project as a CLI project, which will bring in AoT. But for now this example app is in maintenance mode.
